SELECT UF, QTD_APOSTAS, VALOR_ARRECADADO
FROM (SELECT cid.UF UF, 
      TO_CHAR(COUNT(1), '999G999G999') QTD_APOSTAS,
      TO_CHAR(SUM(VALOR), '999G999G999D99') VALOR_ARRECADADO
      FROM APOSTA apo
      LEFT JOIN CIDADE cid ON apo.IDCIDADE = cid.IDCIDADE
      WHERE apo.IDCONCURSO = 1824
      GROUP BY cid.UF
      ORDER BY QTD_APOSTAS DESC)
WHERE ROWNUM <= 5;